# Generated by Django 3.2.20 on 2023-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_order', models.IntegerField()),
                ('course_active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
