# Generated by Django 3.2.20 on 2023-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teacher_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacher_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
