# Generated by Django 3.2.20 on 2023-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20230721_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
