# Generated by Django 3.2.20 on 2023-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_peoplesay'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplesay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people_images'),
        ),
    ]
