# Generated by Django 3.2.20 on 2023-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_peoplesay_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(upload_to='articles_images')),
                ('date', models.DateField()),
                ('article_title', models.CharField(max_length=50)),
                ('article_desc', models.TextField()),
            ],
        ),
    ]
