# Generated by Django 3.2.20 on 2023-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_latestarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('msg', models.TextField()),
            ],
            options={
                'ordering': ['f_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='latestarticles',
            options={'ordering': ['article_title']},
        ),
    ]
